use std::fmt::Write;

use thiserror::Error;
use thyllore_spirv_reflect::{ReflectedBlock, ReflectedMember};

use super::parse::{
    slang_type_name, split_top_level, strip_suffix_index, CppExport, CppField, CppModule,
    CppStruct, UniformPassing,
};
use crate::gpu_block_codegen::snake_case;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum CppAbiCodegenError {
    #[error("`{context}` has C++ type `{type_name}` which has no Rust mapping")]
    UnmappedType { context: String, type_name: String },
    #[error("struct `{0}` is not defined in the generated C++")]
    UnknownStruct(String),
    #[error("`{block}` declares `{member}` in SPIR-V but the C++ struct `{cpp_struct}` has no such field")]
    MemberMissingInCpp {
        block: String,
        member: String,
        cpp_struct: String,
    },
}

const KERNEL_CONTEXT_RUST: &str = "*const KernelContext";

/// The `extern "C"` block plus the context and vector structs the exports take. `block_rust_type`
/// is the Rust path of the uniform block the module reads through its context, if any.
pub fn rust_bindings(
    module: &CppModule,
    stem: &str,
    block_rust_type: Option<&str>,
) -> Result<String, CppAbiCodegenError> {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by build.rs from {stem}.cpp; do not edit.\n"
    );

    write_context_structs(&mut out, &module.uniform, block_rust_type)?;
    write_vector_structs(&mut out, &module.exports);

    out.push_str("extern \"C\" {\n");
    for export in &module.exports {
        let _ = writeln!(out, "    {}", rust_signature(export)?);
    }
    out.push_str("}\n");
    Ok(out)
}

fn write_context_structs(
    out: &mut String,
    uniform: &UniformPassing,
    block_rust_type: Option<&str>,
) -> Result<(), CppAbiCodegenError> {
    let block_rust_type = block_rust_type.unwrap_or("()");
    match uniform {
        UniformPassing::None => {}
        UniformPassing::ByPointer {
            field,
            other_globals,
            ..
        } => {
            write_global_params(out, field, block_rust_type, other_globals)?;
            out.push_str(
                "#[repr(C)]\nstruct KernelContext {\n    global_params: *const GlobalParams,\n}\n\n",
            );
        }
        UniformPassing::ByValue { field, .. } => {
            let _ = writeln!(
                out,
                "#[repr(C)]\nstruct KernelContext {{\n    {field}: {block_rust_type},\n}}\n"
            );
        }
    }
    Ok(())
}

/// Every global of the module in declaration order: the block as a pointer, resources as opaque
/// handles of the prelude's size, so `GlobalParams` has the C++ layout whatever comes after the block.
fn write_global_params(
    out: &mut String,
    block_field: &str,
    block_rust_type: &str,
    other_globals: &[CppField],
) -> Result<(), CppAbiCodegenError> {
    let mut fields = vec![(
        block_field.to_string(),
        format!("*const {block_rust_type}"),
        block_field.to_string(),
    )];
    for global in other_globals {
        let words = resource_handle_words(&global.type_name).ok_or_else(|| {
            CppAbiCodegenError::UnmappedType {
                context: "GlobalParams_0".into(),
                type_name: global.type_name.clone(),
            }
        })?;
        let name = snake_case(strip_suffix_index(&global.name));
        let (rust_type, initializer) = if words == 1 {
            ("*const ()".to_string(), "std::ptr::null()".to_string())
        } else {
            (
                format!("[*const (); {words}]"),
                format!("[std::ptr::null(); {words}]"),
            )
        };
        fields.push((name, rust_type, initializer));
    }

    out.push_str("#[repr(C)]\nstruct GlobalParams {\n");
    for (name, rust_type, _) in &fields {
        let _ = writeln!(out, "    {name}: {rust_type},");
    }
    out.push_str("}\n\n");

    let _ = writeln!(
        out,
        "impl GlobalParams {{\n    fn new({block_field}: *const {block_rust_type}) -> Self {{\n        Self {{"
    );
    for (name, _, initializer) in &fields {
        if name == block_field {
            let _ = writeln!(out, "            {name},");
        } else {
            let _ = writeln!(out, "            {name}: {initializer},");
        }
    }
    out.push_str("        }\n    }\n}\n\n");
    Ok(())
}

/// Pointer-sized words a prelude resource type occupies (`Texture2D { ITexture* }`,
/// `StructuredBuffer { T* data; size_t count; }`).
fn resource_handle_words(cpp_type: &str) -> Option<usize> {
    let base = cpp_type.split('<').next()?.trim();
    match base {
        "StructuredBuffer" | "RWStructuredBuffer" => Some(2),
        _ if base.starts_with("Texture")
            || base.starts_with("RWTexture")
            || base.starts_with("Sampler") =>
        {
            Some(1)
        }
        _ => None,
    }
}

fn global_params_size(other_globals: &[CppField]) -> Option<usize> {
    let words = other_globals
        .iter()
        .map(|global| resource_handle_words(&global.type_name))
        .sum::<Option<usize>>()?;
    Some(std::mem::size_of::<usize>() * (1 + words))
}

fn write_vector_structs(out: &mut String, exports: &[CppExport]) {
    let mentioned = |type_name: &str| {
        exports.iter().any(|export| {
            export.return_type.starts_with(type_name)
                || export
                    .params
                    .iter()
                    .any(|param| param.type_name.starts_with(type_name))
        })
    };
    for (cpp, rust, fields) in [
        ("Vector<float, 2>", "Float2", "    x: f32,\n    y: f32,\n"),
        (
            "Vector<float, 3>",
            "Float3",
            "    x: f32,\n    y: f32,\n    z: f32,\n",
        ),
        (
            "Vector<float, 4>",
            "Float4",
            "    x: f32,\n    y: f32,\n    z: f32,\n    w: f32,\n",
        ),
    ] {
        if mentioned(cpp) {
            let _ = writeln!(out, "#[repr(C)]\nstruct {rust} {{\n{fields}}}\n");
        }
    }
}

fn rust_signature(export: &CppExport) -> Result<String, CppAbiCodegenError> {
    let params = export
        .params
        .iter()
        .map(|param| {
            let rust_type = rust_param_type(&param.type_name, &export.name)?;
            let name = if rust_type == KERNEL_CONTEXT_RUST {
                "ctx".to_string()
            } else {
                snake_case(strip_suffix_index(&param.name))
            };
            Ok(format!("{name}: {rust_type}"))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");

    let return_type = rust_param_type(&export.return_type, &export.name)?;
    if return_type == "()" {
        Ok(format!("fn {}({params});", export.name))
    } else {
        Ok(format!("fn {}({params}) -> {return_type};", export.name))
    }
}

fn rust_param_type(cpp_type: &str, context: &str) -> Result<String, CppAbiCodegenError> {
    let cpp_type = cpp_type.trim();
    if let Some(pointee) = cpp_type.strip_suffix('*') {
        let pointee = pointee.trim();
        if pointee.starts_with("KernelContext_") {
            return Ok(KERNEL_CONTEXT_RUST.to_string());
        }
        return Ok(format!("*mut {}", rust_param_type(pointee, context)?));
    }
    let mapped = match cpp_type {
        "void" => "()",
        "float" => "f32",
        "int32_t" | "int" => "i32",
        "uint32_t" => "u32",
        "bool" => "bool",
        "Vector<float, 2>" => "Float2",
        "Vector<float, 3>" => "Float3",
        "Vector<float, 4>" => "Float4",
        other if is_plain_struct_name(other) => slang_type_name(other),
        other => {
            return Err(CppAbiCodegenError::UnmappedType {
                context: context.to_string(),
                type_name: other.to_string(),
            })
        }
    };
    Ok(mapped.to_string())
}

fn is_plain_struct_name(type_name: &str) -> bool {
    type_name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_')
        && type_name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
}

/// The uniform block as the C++ compiler lays it out (every scalar 4 bytes, 4-aligned, padding
/// explicit), in the vocabulary of SPIR-V reflection so the same codegen and the same layout
/// comparison serve both sources.
pub fn natural_layout_block(
    module: &CppModule,
    block_cpp_name: &str,
) -> Result<ReflectedBlock, CppAbiCodegenError> {
    let cpp_struct = module
        .find_struct(block_cpp_name)
        .ok_or_else(|| CppAbiCodegenError::UnknownStruct(block_cpp_name.to_string()))?;
    let (members, size) = natural_members(module, cpp_struct, 0)?;
    Ok(ReflectedBlock {
        type_name: slang_type_name(block_cpp_name).to_string(),
        size,
        members,
    })
}

fn natural_members(
    module: &CppModule,
    cpp_struct: &CppStruct,
    base: u32,
) -> Result<(Vec<ReflectedMember>, u32), CppAbiCodegenError> {
    let mut members = Vec::new();
    let mut offset = base;
    for field in &cpp_struct.fields {
        let context = format!("{}::{}", cpp_struct.name, field.name);
        let (type_name, size, nested) = natural_type(module, &field.type_name, offset, &context)?;
        members.push(ReflectedMember {
            name: strip_suffix_index(&field.name).to_string(),
            offset,
            size,
            type_name,
            members: nested,
        });
        offset += size;
    }
    Ok((members, offset - base))
}

fn natural_type(
    module: &CppModule,
    cpp_type: &str,
    offset: u32,
    context: &str,
) -> Result<(String, u32, Vec<ReflectedMember>), CppAbiCodegenError> {
    let unmapped = || CppAbiCodegenError::UnmappedType {
        context: context.to_string(),
        type_name: cpp_type.to_string(),
    };
    let scalar = match cpp_type {
        "float" => Some(("float32", 4)),
        "int32_t" | "int" => Some(("int32", 4)),
        "uint32_t" => Some(("uint32", 4)),
        "Vector<float, 2>" => Some(("float32x2", 8)),
        "Vector<float, 3>" => Some(("float32x3", 12)),
        "Vector<float, 4>" => Some(("float32x4", 16)),
        "Matrix<float, 4, 4>" => Some(("float32x4x4", 64)),
        other if other.starts_with("_MatrixStorage_float4x4_") => Some(("float32x4x4", 64)),
        _ => None,
    };
    if let Some((name, size)) = scalar {
        return Ok((name.to_string(), size, Vec::new()));
    }

    if let Some(arguments) = cpp_type
        .strip_prefix("FixedArray<")
        .and_then(|rest| rest.strip_suffix('>'))
    {
        let parts = split_top_level(arguments, ',');
        let [element, length] = parts.as_slice() else {
            return Err(unmapped());
        };
        let length: u32 = length.trim().parse().map_err(|_| unmapped())?;
        let (element_name, element_size, nested) =
            natural_type(module, element.trim(), offset, context)?;
        return Ok((
            format!("{element_name}[{length}]"),
            element_size * length,
            nested,
        ));
    }

    let nested_struct = module.find_struct(cpp_type).ok_or_else(unmapped)?;
    let (members, size) = natural_members(module, nested_struct, offset)?;
    Ok((slang_type_name(cpp_type).to_string(), size, members))
}

/// Member-by-member differences between the C++ natural layout and the SPIR-V std140 layout,
/// empty when the Rust struct generated from the C++ can be uploaded to the GPU unchanged.
pub fn layout_differences(natural: &ReflectedBlock, spirv: &ReflectedBlock) -> Vec<String> {
    let mut differences = Vec::new();
    if natural.size != spirv.size {
        differences.push(format!(
            "{}: size natural={} std140={}",
            spirv.type_name, natural.size, spirv.size
        ));
    }
    compare_members(
        &natural.members,
        &spirv.members,
        &spirv.type_name,
        &mut differences,
    );
    differences
}

fn compare_members(
    natural: &[ReflectedMember],
    spirv: &[ReflectedMember],
    path: &str,
    differences: &mut Vec<String>,
) {
    for member in spirv {
        let member_path = format!("{path}.{}", member.name);
        let Some(counterpart) = natural.iter().find(|item| item.name == member.name) else {
            differences.push(format!("{member_path}: missing in the C++ struct"));
            continue;
        };
        if counterpart.offset != member.offset {
            differences.push(format!(
                "{member_path}: offset natural={} std140={}",
                counterpart.offset, member.offset
            ));
        }
        if counterpart.size != member.size {
            differences.push(format!(
                "{member_path}: size natural={} std140={}",
                counterpart.size, member.size
            ));
        }
        compare_members(
            &counterpart.members,
            &member.members,
            &member_path,
            differences,
        );
    }
}

/// `static_assert`s appended to the generated C++ so the C++ compiler itself proves the natural
/// layout of `block_cpp_name` matches the std140 offsets reflected from SPIR-V.
pub fn layout_asserts_cpp(
    module: &CppModule,
    block_cpp_name: &str,
    spirv: &ReflectedBlock,
) -> Result<String, CppAbiCodegenError> {
    let cpp_struct = module
        .find_struct(block_cpp_name)
        .ok_or_else(|| CppAbiCodegenError::UnknownStruct(block_cpp_name.to_string()))?;
    let mut out = String::new();
    let _ = writeln!(
        out,
        "\n#include <cstddef>\nstatic_assert(sizeof({block_cpp_name}) == {}, \"{}: C++ natural layout size differs from std140\");",
        spirv.size, spirv.type_name
    );
    write_member_asserts(
        module,
        cpp_struct,
        "",
        &spirv.type_name,
        &spirv.members,
        &mut out,
    )?;

    if let UniformPassing::ByPointer { other_globals, .. } = &module.uniform {
        if let Some(size) = global_params_size(other_globals) {
            let _ = writeln!(
                out,
                "static_assert(sizeof(GlobalParams_0) == {size}, \"GlobalParams_0: the Rust mirror of the module globals has a different size\");"
            );
        }
    }
    Ok(out)
}

fn write_member_asserts(
    module: &CppModule,
    cpp_struct: &CppStruct,
    offset_prefix: &str,
    path: &str,
    spirv: &[ReflectedMember],
    out: &mut String,
) -> Result<(), CppAbiCodegenError> {
    for member in spirv {
        let field = cpp_struct
            .fields
            .iter()
            .find(|field| strip_suffix_index(&field.name) == member.name)
            .ok_or_else(|| CppAbiCodegenError::MemberMissingInCpp {
                block: path.to_string(),
                member: member.name.clone(),
                cpp_struct: cpp_struct.name.clone(),
            })?;
        let member_path = format!("{path}.{}", member.name);
        let offset_expression = format!(
            "{offset_prefix}offsetof({}, {})",
            cpp_struct.name, field.name
        );
        let _ = writeln!(
            out,
            "static_assert({offset_expression} == {}, \"{member_path}: C++ natural layout offset differs from std140\");",
            member.offset
        );
        let _ = writeln!(
            out,
            "static_assert(sizeof({}::{}) == {}, \"{member_path}: C++ natural layout size differs from std140\");",
            cpp_struct.name, field.name, member.size
        );

        if member.members.is_empty() {
            continue;
        }
        let element_type = array_element_type(&field.type_name);
        let nested = module
            .find_struct(element_type)
            .ok_or_else(|| CppAbiCodegenError::UnknownStruct(element_type.to_string()))?;
        write_member_asserts(
            module,
            nested,
            &format!("{offset_expression} + "),
            &member_path,
            &member.members,
            out,
        )?;
    }
    Ok(())
}

fn array_element_type(cpp_type: &str) -> &str {
    cpp_type
        .strip_prefix("FixedArray<")
        .and_then(|rest| rest.strip_suffix('>'))
        .and_then(|arguments| split_top_level(arguments, ',').first().copied())
        .map(str::trim)
        .unwrap_or(cpp_type)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cpp_abi::parse::parse_module;

    const SAMPLE: &str = r#"
struct FlameColorMid_0
{
    Vector<float, 3>  rgb_1;
    float pad0_1;
};

struct FlameTwistMode_0
{
    float kappa_0;
    float omega_0;
};

struct FlameUBO_natural_0
{
    _MatrixStorage_float4x4_ColMajornatural_0 model_0;
    FlameColorMid_0 colorMid_0;
    FixedArray<FlameTwistMode_0, 2>  modes_0;
    float time_0;
    float pad0_9;
    float pad1_6;
    float pad2_1;
};

struct GlobalParams_0
{
    FlameUBO_natural_0* flame_0;
    Texture2D<Vector<float, 4> > flameSdfSampler_0;
};

struct KernelContext_0
{
    GlobalParams_0* globalParams_0;
};

SLANG_PRELUDE_EXPORT
Vector<float, 3>  thylloreFlameBranchPullBack(Vector<float, 3>  p_0, KernelContext_0 * kernelContext_0)
{
}

SLANG_PRELUDE_EXPORT
void thylloreFlameJvp(Vector<float, 3>  p_1, Vector<float, 3> * dirOut_0, KernelContext_0 * kernelContext_1)
{
}
"#;

    #[test]
    fn bindings_declare_context_vectors_and_externs() {
        let module = parse_module(SAMPLE).unwrap();
        let bindings =
            rust_bindings(&module, "flame_exports", Some("crate::flame::FlameUBO")).unwrap();
        assert_eq!(
            bindings,
            "// Generated by build.rs from flame_exports.cpp; do not edit.\n\
             \n\
             #[repr(C)]\n\
             struct GlobalParams {\n\
             \x20   flame: *const crate::flame::FlameUBO,\n\
             \x20   flame_sdf_sampler: *const (),\n\
             }\n\
             \n\
             impl GlobalParams {\n\
             \x20   fn new(flame: *const crate::flame::FlameUBO) -> Self {\n\
             \x20       Self {\n\
             \x20           flame,\n\
             \x20           flame_sdf_sampler: std::ptr::null(),\n\
             \x20       }\n\
             \x20   }\n\
             }\n\
             \n\
             #[repr(C)]\n\
             struct KernelContext {\n\
             \x20   global_params: *const GlobalParams,\n\
             }\n\
             \n\
             #[repr(C)]\n\
             struct Float3 {\n\
             \x20   x: f32,\n\
             \x20   y: f32,\n\
             \x20   z: f32,\n\
             }\n\
             \n\
             extern \"C\" {\n\
             \x20   fn thylloreFlameBranchPullBack(p: Float3, ctx: *const KernelContext) -> Float3;\n\
             \x20   fn thylloreFlameJvp(p: Float3, dir_out: *mut Float3, ctx: *const KernelContext);\n\
             }\n"
        );
    }

    #[test]
    fn natural_layout_matches_std140_for_explicitly_padded_structs() {
        let module = parse_module(SAMPLE).unwrap();
        let block = natural_layout_block(&module, "FlameUBO_natural_0").unwrap();
        assert_eq!(block.type_name, "FlameUBO");
        assert_eq!(block.size, 64 + 16 + 16 + 16);
        assert_eq!(block.members[1].type_name, "FlameColorMid");
        assert_eq!(block.members[1].members[1].name, "pad0");
        assert_eq!(block.members[1].members[1].offset, 76);
        assert_eq!(block.members[2].type_name, "FlameTwistMode[2]");
        assert_eq!(block.members[2].size, 16);
        assert_eq!(block.members[2].members[1].offset, 84);
        assert_eq!(block.members[3].offset, 96);
        assert_eq!(layout_differences(&block, &block), Vec::<String>::new());
    }

    #[test]
    fn asserts_walk_nested_structs_with_absolute_offsets() {
        let module = parse_module(SAMPLE).unwrap();
        let block = natural_layout_block(&module, "FlameUBO_natural_0").unwrap();
        let asserts = layout_asserts_cpp(&module, "FlameUBO_natural_0", &block).unwrap();
        assert!(asserts.contains("static_assert(sizeof(FlameUBO_natural_0) == 112,"));
        assert!(asserts.contains("static_assert(offsetof(FlameUBO_natural_0, colorMid_0) + offsetof(FlameColorMid_0, pad0_1) == 76,"));
        assert!(asserts.contains("static_assert(offsetof(FlameUBO_natural_0, modes_0) + offsetof(FlameTwistMode_0, omega_0) == 84,"));
        assert!(asserts.contains("static_assert(sizeof(FlameUBO_natural_0::modes_0) == 16,"));
        assert!(asserts.contains(&format!(
            "static_assert(sizeof(GlobalParams_0) == {},",
            2 * std::mem::size_of::<usize>()
        )));
    }

    #[test]
    fn layout_differences_name_the_drifted_member() {
        let module = parse_module(SAMPLE).unwrap();
        let natural = natural_layout_block(&module, "FlameUBO_natural_0").unwrap();
        let mut spirv = natural.clone();
        spirv.members[3].offset = 100;
        spirv.members[1].members[0].name = "rgba".into();
        assert_eq!(
            layout_differences(&natural, &spirv),
            vec![
                "FlameUBO.colorMid.rgba: missing in the C++ struct".to_string(),
                "FlameUBO.time: offset natural=96 std140=100".to_string(),
            ]
        );
    }

    #[test]
    fn unknown_types_fail_instead_of_leaking_cpp_names() {
        let module =
            parse_module("SLANG_PRELUDE_EXPORT\nvoid f(Matrix<float, 4, 4> m_0)\n{\n}\n").unwrap();
        assert_eq!(
            rust_bindings(&module, "x", None),
            Err(CppAbiCodegenError::UnmappedType {
                context: "f".into(),
                type_name: "Matrix<float, 4, 4>".into()
            })
        );
    }
}
