# cargo-about configuration
# Generate: cargo about generate about.hbs > THIRD_PARTY_CARGO_LICENSES.html
# Docs: https://embarkstudios.github.io/cargo-about/

accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "Zlib",
    "0BSD",
    "Unlicense",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "PDDL-1.0",
    "CDLA-Permissive-2.0",
    "OpenSSL",
    "LGPL-2.1-or-later",
]

ignore-build-dependencies = false
ignore-dev-dependencies = true
filter-noassertion = true
