#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SCENE=""
BUILD_MODE="debug"
PLATFORM="linux_x86_64"
REBUILD_ZIP=1
GUI_ARGS=()
DEFAULT_SCENE="water.blend"

usage() {
    cat <<USAGE
Usage: $0 [--skip-build] [--release] [--software-gl] [scene.blend]

Builds the water addon ZIP (scripts/blender/water/build_addon.sh), then
launches the pristine Blender Docker image on the NVIDIA GPU
(blender/docker/run_gui.sh) with the ZIP installed into a fresh profile,
opens the scene (default: blender/water.blend = camera + light + one water
torus, generated by scripts/blender/water/make_scene.py when missing or older
than the ZIP) and embeds a water torus if the scene has none, so the viewport
draw handler can be checked at once. Blender's console output is mirrored to
<repo>/log/log_blender_water.log.

Options:
  --skip-build         Reuse the newest dist/thyllore_water*-$PLATFORM.zip
  --release            Build/launch the release ZIP (no debug panel) instead of debug
  --software-gl        Passed through to run_gui.sh (Mesa llvmpipe)
  -h, --help           Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-build) REBUILD_ZIP=0; shift ;;
        --release) BUILD_MODE="release"; shift ;;
        --software-gl) GUI_ARGS+=(--software-gl); shift ;;
        -h|--help) usage; exit 0 ;;
        *) SCENE="$1"; shift ;;
    esac
done

if [[ -z "$SCENE" ]]; then
    SCENE="$REPO_ROOT/blender/$DEFAULT_SCENE"
fi

ZIP_BASENAME="thyllore_water"
if [[ "$BUILD_MODE" == "debug" ]]; then
    ZIP_BASENAME="thyllore_water_debug"
fi
if [[ "$REBUILD_ZIP" -eq 1 ]]; then
    bash "$REPO_ROOT/scripts/blender/water/build_addon.sh" --platform "$PLATFORM" --build-mode "$BUILD_MODE"
fi
ZIP="$(ls -t "$REPO_ROOT"/dist/"$ZIP_BASENAME"-*-"$PLATFORM".zip | head -1)"

if [[ "$SCENE" == "$REPO_ROOT/blender/$DEFAULT_SCENE" && ( ! -f "$SCENE" || "$ZIP" -nt "$SCENE" ) ]]; then
    echo "[water/launch] generating $SCENE (missing or older than $(basename "$ZIP"))"
    docker run --rm -v "$REPO_ROOT:/workspace:ro" -v "$(dirname "$ZIP"):/zips:ro" -v "$REPO_ROOT/blender:/out" thyllore-blender-smoke bash -c "
        export HOME=/tmp/blender_home && mkdir -p \"\$HOME\" &&
        blender --command extension install-file -r user_default --enable /zips/$(basename "$ZIP") >/dev/null &&
        blender -b --python-exit-code 1 --python /workspace/scripts/blender/water/make_scene.py -- /out/$DEFAULT_SCENE
    "
fi

LOG="$REPO_ROOT/log/log_blender_water.log"
mkdir -p "$REPO_ROOT/log"
echo "[water/launch] launching Blender (docker, NVIDIA) with $SCENE"
echo "[water/launch] Blender stdout/stderr -> $LOG"
bash "$REPO_ROOT/blender/docker/run_gui.sh" \
    --zip "$ZIP" --scene "$SCENE" \
    --python "$REPO_ROOT/scripts/blender/water/embed.py" \
    ${GUI_ARGS[@]+"${GUI_ARGS[@]}"} 2>&1 | tee "$LOG"
