//! Reorders the embedding router's top two when they are opposite poles of one axis.
//!
//! This replaced a keyword rule table that returned a route outright. That table
//! bypassed the similarity threshold, so a wrong keyword match was executed
//! unguarded: on held-out it fired for 47 of 128 utterances at 0.468 precision and
//! cost 19 cases, because its highest-firing rules keyed on the domain's most
//! common words (`play`, `再生`, `loop`, `stop`) and no blocklist can make those
//! precise. Twelve of its rules were correct every time they fired and changed
//! nothing, the encoder having already agreed.
//!
//! What survives is the part the encoder genuinely cannot do: telling apart the two
//! ends of an axis. Three of the held-out confusions separated their two candidates
//! by 0.005 cosine or less, which is a coin flip. Two structural conditions bound the
//! damage this can do. The pair must be declared opposite poles in `../data/polarity_groups.json`,
//! so a wrong swap can only ever land on a route the encoder itself ranked second.
//! And the deciding term must be one no other route's exemplars use, which is why
//! the table is generated by `AnimationModelTraining scripts/helm_router/derive_polarity_terms.py`
//! rather than written by hand — filler words like `and` and conjugation fragments
//! like `生成し` pass a looser test and then overturn correct answers.
//!
//! Categorical enums are deliberately not groups even though their schema shape is
//! identical. The encoder separates `walk` from `jump` reliably, so a tie-break
//! there has nothing to win and was measured losing.
//!
//! `AnimationModelTraining scripts/helm_router/polarity.py` is the reference: it produced the
//! measured accuracy, so this file is correct only insofar as it answers the same
//! way. `polarity_tiebreak_cases.json` records those answers over every utterance
//! the repository has, and the differential test below holds this code to them.

use std::collections::HashMap;
use std::sync::LazyLock;

use serde::Deserialize;

use crate::helm::components::route::Route;

const POLARITY_GROUPS_JSON: &str = include_str!("../data/polarity_groups.json");

#[derive(Deserialize)]
struct RawTable {
    groups: HashMap<String, HashMap<String, Vec<String>>>,
}

struct PolarityAxis {
    name: String,
    terms: Vec<String>,
}

static POLARITY_AXES: LazyLock<HashMap<String, PolarityAxis>> = LazyLock::new(load_polarity_axes);

fn load_polarity_axes() -> HashMap<String, PolarityAxis> {
    let raw: RawTable = serde_json::from_str(POLARITY_GROUPS_JSON)
        .expect("polarity_groups.json is embedded at compile time and must parse");

    let mut axes = HashMap::new();
    for (axis_name, members) in raw.groups {
        for (route_id, terms) in members {
            let route = Route::from_id(&route_id)
                .unwrap_or_else(|| panic!("polarity group names unknown route {route_id}"));
            axes.insert(
                route.id(),
                PolarityAxis {
                    name: axis_name.clone(),
                    terms,
                },
            );
        }
    }
    axes
}
pub fn embedded_exemplars_sha256() -> Option<String> {
    let parsed: serde_json::Value = serde_json::from_str(POLARITY_GROUPS_JSON).ok()?;
    parsed.get("exemplars_sha256")?.as_str()?.to_string().into()
}

fn find_axis(route: Route) -> Option<&'static PolarityAxis> {
    POLARITY_AXES.get(&route.id())
}

pub fn share_axis(first: Route, second: Route) -> bool {
    match (find_axis(first), find_axis(second)) {
        (Some(left), Some(right)) => left.name == right.name,
        _ => false,
    }
}

fn count_polarity_evidence(normalized: &str, route: Route) -> usize {
    find_axis(route).map_or(0, |axis| {
        axis.terms
            .iter()
            .filter(|term| normalized.contains(term.as_str()))
            .count()
    })
}

/// Promotes the runner-up when the utterance names its pole and not the leader's.
///
/// `ranked` must be the embedding router's output in descending score order. Only
/// the first two entries are read — anything below them was never in contention, and
/// letting a third route win would be the rule table's mistake again.
pub fn break_polarity_tie(normalized: &str, ranked: &[(Route, f32)]) -> Option<TieBreakOutcome> {
    let leader = ranked.first()?.0;
    if ranked.len() < 2 {
        return Some(TieBreakOutcome::NotApplicable(leader));
    }

    let runner_up = ranked[1].0;
    if !share_axis(leader, runner_up) {
        return Some(TieBreakOutcome::NotApplicable(leader));
    }

    let leader_evidence = count_polarity_evidence(normalized, leader);
    let runner_up_evidence = count_polarity_evidence(normalized, runner_up);
    if runner_up_evidence > leader_evidence {
        return Some(TieBreakOutcome::Decided(runner_up));
    }
    Some(TieBreakOutcome::Undecided(leader))
}

/// The outcome of the polarity tie-break.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum TieBreakOutcome {
    /// Same axis and polarity evidence decided: the winner is not the leader.
    Decided(Route),
    /// Not a same-axis pair (or only one candidate): the leader stands by default.
    NotApplicable(Route),
    /// Same axis but polarity evidence did not decide: the leader stands by default.
    Undecided(Route),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::helm::components::route::ALL_ROUTES;
    use crate::helm::components::tool_call::{
        SeekPosition, ShotPreset, SpeedPreset, VisibilityState,
    };
    use crate::helm::systems::normalize::normalize_utterance;
    use std::collections::HashSet;

    fn resolve(utterance: &str, ranked: &[(Route, f32)]) -> Route {
        let outcome = break_polarity_tie(&normalize_utterance(utterance), ranked)
            .expect("a non-empty ranking always resolves");
        match outcome {
            TieBreakOutcome::Decided(r)
            | TieBreakOutcome::NotApplicable(r)
            | TieBreakOutcome::Undecided(r) => r,
        }
    }

    fn assert_promotes(utterance: &str, leader: Route, runner_up: Route) {
        assert_eq!(
            resolve(utterance, &[(leader, 0.9), (runner_up, 0.5)]),
            runner_up,
            "for {utterance:?}"
        );
    }

    fn assert_keeps_leader(utterance: &str, leader: Route, runner_up: Route) {
        assert_eq!(
            resolve(utterance, &[(leader, 0.9), (runner_up, 0.5)]),
            leader,
            "for {utterance:?}"
        );
    }

    #[test]
    fn the_generated_table_parses_and_every_route_id_resolves() {
        assert!(!POLARITY_AXES.is_empty());
        for route_id in POLARITY_AXES.keys() {
            assert!(Route::from_id(route_id).is_some(), "{route_id}");
        }
    }

    #[test]
    fn terms_are_lowercase_so_they_match_normalized_text() {
        for (route_id, axis) in POLARITY_AXES.iter() {
            for term in &axis.terms {
                assert_eq!(term.as_str(), term.to_lowercase(), "in {route_id}");
            }
        }
    }

    /// A term shared by both poles of an axis can never decide between them, so its
    /// presence in the table would mean the generator's exclusivity test regressed.
    #[test]
    fn no_term_appears_on_both_poles_of_one_axis() {
        let mut seen_per_axis: HashMap<&str, HashSet<&str>> = HashMap::new();
        for axis in POLARITY_AXES.values() {
            let seen = seen_per_axis.entry(axis.name.as_str()).or_default();
            for term in &axis.terms {
                assert!(seen.insert(term.as_str()), "{} in {}", term, axis.name);
            }
        }
    }

    #[test]
    fn categorical_enums_are_not_polarity_axes() {
        for route in ALL_ROUTES {
            let is_categorical = matches!(
                route,
                Route::GenerateMotion(_) | Route::FocusCamera(_) | Route::SelectObject
            );
            assert_eq!(
                find_axis(route).is_some(),
                !is_categorical && expected_on_an_axis(route),
                "{}",
                route.id()
            );
        }
    }

    fn expected_on_an_axis(route: Route) -> bool {
        matches!(
            route,
            Route::SeekTime(_)
                | Route::SetPlaybackSpeed(_)
                | Route::SetObjectVisibility(_)
                | Route::PauseAnimation
                | Route::StopAnimation
                | Route::Undo
                | Route::Redo
                | Route::CameraShot(ShotPreset::DollyIn)
                | Route::CameraShot(ShotPreset::DollyOut)
                | Route::CameraShot(ShotPreset::CraneUp)
                | Route::CameraShot(ShotPreset::CraneDown)
        )
    }

    /// Both are held-out utterances the encoder ranked the wrong way round by 0.005
    /// cosine, which is a coin flip. They are the clearest case for the mechanism, so
    /// they are asserted against the generated table rather than described in a comment.
    #[test]
    fn keyframe_direction_is_recovered_from_a_coin_flip() {
        assert_promotes(
            "hop to the key before this one",
            Route::SeekTime(SeekPosition::NextKey),
            Route::SeekTime(SeekPosition::PrevKey),
        );
        assert_promotes(
            "キーフレームを一つ先に進めて",
            Route::SeekTime(SeekPosition::PrevKey),
            Route::SeekTime(SeekPosition::NextKey),
        );
    }

    #[test]
    fn timeline_bounds_are_recovered() {
        assert_promotes(
            "take me to where the animation finishes",
            Route::SeekTime(SeekPosition::Start),
            Route::SeekTime(SeekPosition::End),
        );
    }

    /// `forward` is an exclusive term for the next-key pole (no other route's
    /// exemplars use it), so it decides in favor of NextKey.
    #[test]
    fn a_pole_word_exclusive_to_one_route_decides() {
        assert_promotes(
            "nudge the playhead to the upcoming key",
            Route::SeekTime(SeekPosition::PrevKey),
            Route::SeekTime(SeekPosition::NextKey),
        );
    }

    #[test]
    fn the_playback_degree_is_recovered() {
        assert_promotes(
            "普通のスピードで流して",
            Route::SetPlaybackSpeed(SpeedPreset::Fast),
            Route::SetPlaybackSpeed(SpeedPreset::Normal),
        );
    }

    /// The weakest of the recovered cases: `一つ` is a numeral, not a direction, and
    /// it only qualifies because no other route's exemplars happen to use it. Kept
    /// because the derivation must not be hand-corrected case by case, but it is the
    /// first thing to lose if the undo exemplars are rewritten.
    #[test]
    fn edit_history_direction_is_recovered() {
        assert_promotes("変更を一つ巻き戻して", Route::Redo, Route::Undo);
    }

    /// The encoder's ordering is the default. Without a term for either pole there
    /// is nothing to reorder on, and a tie-break that guesses would be the rule
    /// table again.
    #[test]
    fn an_utterance_with_no_polarity_term_keeps_the_encoders_order() {
        assert_keeps_leader(
            "do that thing",
            Route::SeekTime(SeekPosition::NextKey),
            Route::SeekTime(SeekPosition::PrevKey),
        );
    }

    #[test]
    fn a_pair_from_different_axes_is_never_reordered() {
        assert_keeps_leader(
            "hide the cube before this one",
            Route::SetObjectVisibility(VisibilityState::Hide),
            Route::SeekTime(SeekPosition::PrevKey),
        );
    }

    /// Only the top two are in contention. A third route holding the strongest
    /// keyword evidence must not be able to climb over both.
    #[test]
    fn a_third_place_route_cannot_win() {
        let ranked = [
            (Route::SeekTime(SeekPosition::NextKey), 0.9),
            (Route::PlayAnimation, 0.8),
            (Route::SeekTime(SeekPosition::PrevKey), 0.1),
        ];
        assert_eq!(
            resolve("hop to the key before this one", &ranked),
            Route::SeekTime(SeekPosition::NextKey)
        );
    }

    #[test]
    fn a_single_candidate_is_returned_unchanged() {
        assert_eq!(
            resolve("anything at all", &[(Route::SaveScene, 0.4)]),
            Route::SaveScene
        );
    }

    #[test]
    fn an_empty_ranking_resolves_to_nothing() {
        assert_eq!(break_polarity_tie("play it", &[]), None);
    }

    const EXPORTED_CASES_JSON: &str = include_str!("../data/polarity_tiebreak_cases.json");

    /// The Python answers, over every utterance in the exemplars and both datasets.
    ///
    /// The measured 0.845 came from `polarity.py`. Anything this file does
    /// differently — a normalization step, substring semantics, which routes count
    /// as one axis — moves the engine off that number without failing a test, so
    /// the two implementations are compared case by case rather than trusted to
    /// have been written from the same description.
    #[derive(Deserialize)]
    struct ExportedCases {
        table_term_counts: HashMap<String, usize>,
        cases: Vec<ExportedCase>,
    }

    #[derive(Deserialize)]
    struct ExportedCase {
        utterance: String,
        normalized: String,
        resolutions: Vec<(String, String, String)>,
    }

    fn load_exported_cases() -> ExportedCases {
        serde_json::from_str(EXPORTED_CASES_JSON)
            .expect("polarity_tiebreak_cases.json is generated and must parse")
    }

    /// Editing `exemplars.jsonl` regenerates the term table, which makes the
    /// recorded answers describe a table this build no longer has. Comparing the
    /// term counts turns that staleness into a failure that names the regeneration
    /// step, rather than letting the resolutions pass or fail for the wrong reason.
    #[test]
    fn the_exported_cases_were_generated_from_the_embedded_table() {
        let exported = load_exported_cases();
        let embedded: HashMap<String, usize> = POLARITY_AXES
            .iter()
            .map(|(route_id, axis)| (route_id.clone(), axis.terms.len()))
            .collect();

        assert_eq!(
            exported.table_term_counts, embedded,
            "re-run derive_polarity_terms.py then export_tiebreak_cases.py"
        );
    }

    #[test]
    fn normalization_agrees_with_the_python_reference() {
        for case in load_exported_cases().cases {
            assert_eq!(
                normalize_utterance(&case.utterance),
                case.normalized,
                "for {:?}",
                case.utterance
            );
        }
    }

    #[test]
    fn every_exported_resolution_agrees_with_the_python_reference() {
        for case in load_exported_cases().cases {
            for (leader, runner_up, expected) in &case.resolutions {
                let ranked = [(route_named(leader), 1.0), (route_named(runner_up), 0.9)];
                assert_eq!(
                    resolve(&case.utterance, &ranked).id(),
                    *expected,
                    "for {:?} ranked {leader} over {runner_up}",
                    case.utterance
                );
            }
        }
    }

    fn route_named(route_id: &str) -> Route {
        Route::from_id(route_id).unwrap_or_else(|| panic!("exported unknown route {route_id}"))
    }
}
