[env]
ORT_DYLIB_PATH = { value = "vendor/onnxruntime/onnxruntime-win-x64-1.23.2/lib/onnxruntime.dll", relative = true }

[target.aarch64-linux-android]
#ar = "NDK/arm64/bin/aarch64-linux-android-ar"
#linker = "NDK/arm64/bin/aarch64-linux-android-clang.cmd"

[target.armv7-linux-androideabi]
#ar = "NDK/arm/bin/arm-linux-androideabi-ar"
#linker = "NDK/arm/bin/arm-linux-androideabi-clang.cmd"

[target.i686-linux-android]
#ar = "NDK/x86/bin/i686-linux-android-ar"
#linker = "NDK/x86/bin/i686-linux-android-clang.cmd"