#!/usr/bin/env bash
set -euo pipefail

# Launches the engine with a curve copilot mode (--curve-copilot <mode>).
# full mode sources the worker connection env from a gitignored env file so
# secrets never live in tracked files.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_ENV_FILE="$REPO_ROOT/.config/curve_copilot_full.env"

MODE="private"
ENV_FILE="$DEFAULT_ENV_FILE"
CARGO_ARGS=()

usage() {
    cat <<EOF
Usage: ./run.sh engine [private|degrade|full] [options] [cargo args...]

Launches the engine via cargo run. The mode maps to --curve-copilot:
  private   ctx64, no sending (default; same as launching without a flag)
  degrade   ctx32 (older half of the context window zero-padded)
  full      ctx64 + feedback sending to the worker

Options:
  --env-file PATH   env file for full mode (default: .config/curve_copilot_full.env)
  -h, --help        Show this help

Any other argument is passed to cargo run before "--", e.g.:
  ./run.sh engine full --features auto-rig --release

full mode env file (gitignored) must define:
  THYLLORE_FEEDBACK_TEST_ENDPOINT=https://<worker>-test.workers.dev/v1/feedback
  THYLLORE_INGEST_TOKEN=<ingest token>
  # Optional: production endpoint, used by addon builds via --env prod:
  THYLLORE_FEEDBACK_PROD_ENDPOINT=https://<worker>.workers.dev/v1/feedback
  # Optional. Baked at compile time; required for the "full ctx kept" log
  # (verifies the full token returned by the worker):
  THYLLORE_FULL_TOKEN_PUBKEY_B64=<base64 of the 32 raw public key bytes>

The engine always runs against the TEST endpoint (exported to the process as
THYLLORE_FEEDBACK_ENDPOINT, the runtime variable the binary reads).

On the first full run the file is generated automatically:
  THYLLORE_FULL_TOKEN_PUBKEY_B64   from secrets/public_key.b64 (gen_license_keypair.sh)
  THYLLORE_FEEDBACK_TEST_ENDPOINT  from the Cloudflare API (test worker URL) when
                               CF_API_TOKEN and CF_ACCOUNT_ID are exported
  THYLLORE_INGEST_TOKEN        cannot be derived (write-only secret) — fill in
                               the value you exported when running src/ml/worker/deploy.sh
EOF
}

resolve_test_worker_endpoint() {
    [[ -n "${CF_API_TOKEN:-}" && -n "${CF_ACCOUNT_ID:-}" ]] || return 0
    command -v curl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1 || return 0

    local worker_name subdomain
    worker_name="$(sed -n 's/^name = "\(.*\)"$/\1/p' "$REPO_ROOT/src/ml/worker/wrangler.toml")"
    [[ -n "$worker_name" ]] || return 0
    subdomain="$(curl -sf -H "Authorization: Bearer $CF_API_TOKEN" \
        "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/subdomain" \
        | jq -r '.result.subdomain // empty')" || return 0
    [[ -n "$subdomain" ]] || return 0
    printf 'https://%s-test.%s.workers.dev/v1/feedback' "$worker_name" "$subdomain"
}

generate_full_env_file() {
    mkdir -p "$(dirname "$ENV_FILE")"

    local pubkey="" endpoint="" pubkey_file=""
    for candidate in "$REPO_ROOT/secrets/public_key.b64" "$REPO_ROOT/src/ml/worker/secrets/public_key.b64"; do
        if [[ -r "$candidate" ]]; then
            pubkey_file="$candidate"
            pubkey="$(tr -d '[:space:]' < "$candidate")"
            break
        fi
    done
    endpoint="$(resolve_test_worker_endpoint)"

    cat > "$ENV_FILE" <<EOF
# Curve Copilot full-mode connection (gitignored; generated by run_engine.sh).
# THYLLORE_INGEST_TOKEN is the value exported when deploying src/ml/worker/deploy.sh;
# it is write-only on Cloudflare and must be filled in here once by hand.
THYLLORE_FEEDBACK_TEST_ENDPOINT=$endpoint
THYLLORE_FEEDBACK_PROD_ENDPOINT=
THYLLORE_INGEST_TOKEN=
THYLLORE_FULL_TOKEN_PUBKEY_B64=$pubkey
EOF
    chmod 600 "$ENV_FILE"
    echo "[run_engine] generated $ENV_FILE" >&2
    if [[ -n "$endpoint" ]]; then
        echo "[run_engine]   endpoint auto-filled: $endpoint" >&2
    fi
    if [[ -n "$pubkey" ]]; then
        echo "[run_engine]   full-token pubkey auto-filled from $pubkey_file" >&2
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        private|degrade|full) MODE="$1"; shift ;;
        --env-file) ENV_FILE="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) CARGO_ARGS+=("$1"); shift ;;
    esac
done

if [[ "$MODE" == "full" ]]; then
    if [[ ! -r "$ENV_FILE" ]]; then
        generate_full_env_file
    fi
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
    export THYLLORE_FEEDBACK_ENDPOINT="${THYLLORE_FEEDBACK_ENDPOINT:-${THYLLORE_FEEDBACK_TEST_ENDPOINT:-}}"

    missing=()
    for var in THYLLORE_FEEDBACK_TEST_ENDPOINT THYLLORE_INGEST_TOKEN; do
        [[ -z "${!var:-}" ]] && missing+=("$var")
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        echo "full mode still needs: ${missing[*]}" >&2
        echo "Fill them in once in $ENV_FILE (see './run.sh engine --help')." >&2
        exit 2
    fi
fi

cd "$REPO_ROOT"
source "$REPO_ROOT/scripts/lib/onnxruntime.sh"
ensure_onnxruntime
source "$REPO_ROOT/scripts/lib/helm_preflight.sh"
helm_preflight
echo "[run_engine] mode=$MODE cargo args: ${CARGO_ARGS[*]:-(none)}"
exec cargo run "${CARGO_ARGS[@]}" -- --curve-copilot "$MODE"
