FROM thyllore-blender-xvfb:local

RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common gpg-agent \
    && add-apt-repository -y ppa:kisak/kisak-mesa \
    && apt-get update && apt-get install -y --no-install-recommends mesa-vulkan-drivers libgl1-mesa-dri libglx-mesa0 \
    && rm -rf /var/lib/apt/lists/*
