use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use thiserror::Error;
use thyllore_spirv_reflect::{reflect_shader_bytes, ReflectedBlock};

use crate::{
    find_declared_block, generate_gpu_blocks_rust, parse_entry_points, spirv_command,
    GpuBlockCodegenConfig, GpuBlockCodegenError,
};

/// A uniform block read only on the GPU: no CPU Slang module proves a natural layout for it, so
/// its Rust mirror is generated straight from the std140 layout reflected out of the stage that
/// declares it.
pub struct SpirvBlock {
    pub name: &'static str,
    pub stage_source: &'static str,
    pub imports: &'static [&'static str],
}

#[derive(Debug, Error)]
pub enum SpirvBlockError {
    #[error("{stage_source}: {error}")]
    Io {
        stage_source: String,
        error: std::io::Error,
    },
    #[error("{stage_source}: no [shader] entry point")]
    NoEntryPoint { stage_source: String },
    #[error("slangc failed on {stage_source}:\n{stderr}")]
    Slangc {
        stage_source: String,
        stderr: String,
    },
    #[error("cannot run slangc for {stage_source}: {error} (SLANG_ROOT/bin/slangc, default ~/.local/slang)")]
    SlangcUnavailable {
        stage_source: String,
        error: std::io::Error,
    },
    #[error("{stage_source}: {error}")]
    Reflect { stage_source: String, error: String },
    #[error("{stage_source}: SPIR-V declares no uniform block `{name}`")]
    MissingBlock { stage_source: String, name: String },
}

/// Compiles the stage that reads `name` to SPIR-V with the renderer's flags and reflects the block.
pub fn reflect_stage_block(
    name: &str,
    stage_source: &str,
    slang_root: &Path,
    shader_root: &Path,
    out_dir: &Path,
) -> Result<ReflectedBlock, SpirvBlockError> {
    let io = |error| SpirvBlockError::Io {
        stage_source: stage_source.to_string(),
        error,
    };
    let source_path = shader_root.join(stage_source);
    let source = fs::read_to_string(&source_path).map_err(io)?;
    let entry = parse_entry_points(&source)
        .into_iter()
        .next()
        .ok_or_else(|| SpirvBlockError::NoEntryPoint {
            stage_source: stage_source.to_string(),
        })?;

    let spirv_path = out_dir.join(format!("{name}.spv"));
    let output = spirv_command(slang_root, shader_root, &source_path)
        .args(["-entry", &entry.name])
        .args(["-stage", entry.stage.attribute()])
        .arg("-o")
        .arg(&spirv_path)
        .output()
        .map_err(|error| SpirvBlockError::SlangcUnavailable {
            stage_source: stage_source.to_string(),
            error,
        })?;
    if !output.status.success() {
        return Err(SpirvBlockError::Slangc {
            stage_source: stage_source.to_string(),
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }

    let bytes = fs::read(&spirv_path).map_err(io)?;
    let reflection = reflect_shader_bytes(&bytes).map_err(|error| SpirvBlockError::Reflect {
        stage_source: stage_source.to_string(),
        error: error.to_string(),
    })?;
    find_declared_block(&reflection, name).ok_or_else(|| SpirvBlockError::MissingBlock {
        stage_source: stage_source.to_string(),
        name: name.to_string(),
    })
}

/// Rust mirror of a block generated from its std140 layout; `origin` names the SPIR-V it came from.
pub fn generate_spirv_block_rust(
    block: &ReflectedBlock,
    origin: &str,
    imports: &[&str],
) -> Result<String, GpuBlockCodegenError> {
    let config = GpuBlockCodegenConfig {
        header: format!("Generated by build.rs from the std140 block of {origin}; do not edit."),
        imports: imports.iter().map(|import| import.to_string()).collect(),
        extra_derives: BTreeMap::new(),
    };
    generate_gpu_blocks_rust(block, &config)
}
